services:
  backend:
    container_name: bot-notification
    restart: always
    build: .
    volumes:
      - ./src/:/app/src/
    environment:
      DISCORD_CHANNEL_ID: ${DISCORD_CHANNEL_ID}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      APP_PORT: ${APP_PORT}
      DISCORD_ROLE_ID: ${DISCORD_ROLE_ID}
    ports:
      - "${APP_PORT}:${APP_PORT}"