# image de construction (avec TS)
FROM node:lts-alpine AS builder
WORKDIR /app

COPY *.json .
RUN npm i
COPY src src

RUN npm run build

# image de production (pas de TS)
FROM node:lts-alpine
WORKDIR /app
RUN apk --no-cache add curl

COPY package*.json .
RUN npm i --production
COPY --from=builder /app/dist ./dist

CMD npm run start