services:
  frontend:
    container_name: giftchat-staging-frontend
    restart: always
    image: ${FRONTEND_IMAGE}
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --request GET --url 'http://localhost:${FRONTEND_PORT}' || exit 1" ]
      interval: 10s
      retries: 5
      start_period: 20s
    depends_on:
      backend:
        condition: service_healthy
    environment:
      VITE_MODE: prod

  backend:
    container_name: giftchat-staging-backend
    restart: always
    image: ${BACKEND_IMAGE}
    volumes:
      - ./backend/public/:/app/public/
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", 'curl --fail --request POST --header ''Content-Type: application/json'' --url ''http://localhost:${SERVEUR_PORT}'' --data ''{"query":"query { __typename }"}'' || exit 1' ]
      interval: 10s
      retries: 5
      start_period: 20s
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      JWT_SECRET: ${JWT_SECRET}
      SERVEUR_PORT: ${SERVEUR_PORT}
      MODE: prod
      INTERNAL_SECRET_KEY: ${INTERNAL_SECRET_KEY}

  picture-service:
    container_name: giftchat-staging-picture-service
    restart: always
    image: ${PICTURE_SERVICE_IMAGE}
    volumes:
      - ./picture-service/public/:/app/public/
    healthcheck:
      test: [ "CMD-SHELL", 'curl --fail --request POST --header ''Content-Type: application/json'' --url ''http://localhost:${PICTURE_SERVICE_PORT}'' --data ''{"query":"query { __typename }"}'' || exit 1' ]
      interval: 10s
      retries: 5
      start_period: 20s
    environment:
      BACKEND_URL: ${SERVEUR_URL}
      CLIENT_URL: ${FRONTEND_URL}
      APP_PORT: ${PICTURE_SERVICE_PORT}

  message-service:
    container_name: giftchat-staging-message-service
    restart: always
    image: ${MESSAGE_SERVICE_IMAGE}
    environment:
      BACKEND_URL: ${SERVEUR_URL}
      CLIENT_URL: ${FRONTEND_URL}
      MESSAGE_SERVICE_PORT: ${MESSAGE_SERVICE_PORT}
      INTERNAL_SECRET_KEY: ${INTERNAL_SECRET_KEY}
      JWT_SECRET: ${JWT_SECRET}

  database:
    container_name: giftchat-staging-database
    image: postgres
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${DB_DATABASE} -U ${DB_USER}" ]
      interval: 10s
      retries: 5
      start_period: 20s
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - ./persist/database:/var/lib/postgresql

  gateway:
    container_name: giftchat-staging-gateway
    restart: always
    image: ${GATEWAY_IMAGE}
    ports:
      - ${GATEWAY_PORT}:80

